services:
  - type: web
    name: land-registry-app
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: dxlwrxwjl
        sync: false
      - key: 925297674287918
        sync: false
      - key: v7L380npsH5M8UsU5iBrV4IhDkk
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
